language: cpp
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - kubuntu-backports
    packages:
    - cmake
    - libgtest-dev
    - unzip

before_install:
  - "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libao-dev libmpg123-dev libboost-all-dev libncurses5-dev"
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

script:
  - "mkdir build && cd build && cmake ../ && make && cd tests && ./libcrypttests"