language: cpp
compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - kubuntu-backports
    packages:
    - cmake
    - libgtest-dev
    - unzip

before_install:
  - "sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install libao-dev libmpg123-dev libboost-all-dev libncurses5-dev"
  - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"

script:
  - "mkdir build && cd build && cmake ../ && make && cd tests && ./libcrypttests"